<?php

return [
	[
		'slug'		=> 'autoUsername',
		'type'		=> 'radio',
		'default'	=> TRUE,
		'value'		=> '',
		'options'	=> '1=Enabled|0=Disabled',
		'isRequired'=> 0,
		'isGui'		=> 1,
		'module'	=> 'users',
		'order'		=> 964,
	],
	[
		'slug'		=> 'enableProfiles',
		'type'		=> 'radio',
		'default'	=> TRUE,
		'value'		=> '',
		'options'	=> '1=Enabled|0=Disabled',
		'isRequired'=> 1,
		'isGui'		=> 1,
		'module'	=> 'users',
		'order'		=> 963,
	],
	[
		'slug'		=> 'activationEmail',
		'type'		=> 'select',
		'default'	=> TRUE,
		'value'		=> '',
		'options'	=> '0=activate_by_admin|1=activate_by_email|2=no_activation',
		'isRequired'=> 0,
		'isGui'		=> 1,
		'module'	=> 'users',
		'order'		=> 961,
	],
	[
		'slug'		=> 'registeredEmail',
		'type'		=> 'radio',
		'default'	=> TRUE,
		'value'		=> '',
		'options'	=> '1=Enabled|0=Disabled',
		'isRequired'=> 0,
		'isGui'		=> 1,
		'module'	=> 'users',
		'order'		=> 962,
	],
	[
		'slug'		=> 'enableRegistration',
		'type'		=> 'radio',
		'default'	=> TRUE,
		'value'		=> '',
		'options'	=> '1=Enabled|0=Disabled',
		'isRequired'=> 0,
		'isGui'		=> 1,
		'module'	=> 'users',
		'order'		=> 961,
	],
	[
		'slug'		=> 'profileVisibility',
        'type'		=> 'select',
        'default'	=> 'public',
        'value'		=> '',
        'options'	=> 'public=profile_public|owner=profile_owner|hidden=profile_hidden|member=profile_member',
        'isRequired'=> 0,
        'isGui'		=> 1,
        'module'	=> 'users',
        'order'		=> 960,
	],
];